export type GradingType = 'Calculation' | 'Normal' | 'Comment';

export const GRADING_TYPE_VALUE: Record<GradingType, string> = {
  Calculation: '2',
  Normal:      '1',
  Comment:     '0',
};

export const CALCULATION_TYPE_VALUE: Record<string, string> = {
  'Grading conversion': '2',
  'Average':            '0',
  'Sum':                '1',
  'Weight percent':     '3',
};
export type WeightValue = '0' | '' | '1' | '2' | '3';

export interface FieldsConfig {
  calculatedItems: string[]; // Danh sách cột con tham gia tính toán
  calculationType: string;  // numeric ID từ hidden input: 'Grading conversion' = '2', ...
  minColumnsCount: number;  // Số cột con tối thiểu để bật scheme tính toán
}
export interface InputTypeConfig {
 isReadOnly: boolean; // Nếu true thì field này sẽ hiển thị dưới dạng text (không phải input) nhưng vẫn có thể có giá trị để assert
 isInputOrImportExcel: boolean; // Nếu true thì field này sẽ hiển thị dưới dạng input hoặc có thể nhập excel, ngược lại sẽ hiển thị dưới dạng text (read-only)
 isFromTeacherGradebook: boolean; // Nếu true thì field này chỉ có thể nhập từ sổ điểm của giáo viên, không thể nhập thủ công trên giao diện cột điểm
}

export interface ColumnConfig { 
  code: string;
  name: string;
  reportName: string; 
  gradingMechanism: string;
  semesterCode: string;
  semester: string;
  parentGroup: string;
  gradingType: GradingType;
  weight: WeightValue;
  gradingInput: InputTypeConfig;
  isComment: boolean;
  lineNumber: string;
  scheme?: FieldsConfig;// Chỉ có khi gradingType === 'Calculation'
  isRounded?: boolean; // true = ON, false = OFF — assert qua aria-pressed trên dx-switch
  isDisplayOnTotalScoreGradeBook?: boolean;
  isSyncToCanvas?: boolean;
}

export interface GradingBookTemplateDetail {
  code: string;
  finalScore: string;
  columns: ColumnConfig[];
}

export const TH_MOET_DGDK_MUCDATDUOC_DETAIL: GradingBookTemplateDetail = {
  code: 'TH_MOET_DGDK_MUCDATDUOC',
  finalScore: 'CN',
  columns: [
    { code: 'CN',      name: 'Cuối năm', reportName:'',               gradingMechanism: '10', semesterCode: '', semester: '',parentGroup: '',    gradingType: 'Calculation', scheme: { calculatedItems: ['Học kỳ 2'], calculationType: 'Grading conversion', minColumnsCount:1 }, weight: '0', gradingInput: {isReadOnly: true, isInputOrImportExcel: false, isFromTeacherGradebook: false},  isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'HK1',     name: 'Học kỳ 1', reportName:'',               gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1',parentGroup: 'Cuối năm', gradingType: 'Calculation', scheme: { calculatedItems: ['Cuối kỳ 1'], calculationType: 'Grading conversion', minColumnsCount:1 }, weight: '0', gradingInput: {isReadOnly: true, isInputOrImportExcel: false, isFromTeacherGradebook: false},  isComment: false,  lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'HK2',     name: 'Học kỳ 2', reportName:'',               gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2',parentGroup: 'Cuối năm', gradingType: 'Calculation', scheme: { calculatedItems: ['Cuối kỳ 2'], calculationType: 'Grading conversion', minColumnsCount:1 }, weight: '0', gradingInput: {isReadOnly: true, isInputOrImportExcel: false, isFromTeacherGradebook: false},  isComment: false,  lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'GK1',     name: 'Giữa kỳ 1', reportName:'',              gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1',parentGroup: 'Học kỳ 1', gradingType: 'Normal',                               weight: '0', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: true},  isComment: false,  lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook:false, isSyncToCanvas: true },
    { code: 'GK2',     name: 'Giữa kỳ 2', reportName:'',              gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2',parentGroup: 'Học kỳ 2', gradingType: 'Normal',                               weight: '0', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: true},  isComment: false,  lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'CK1',     name: 'Cuối kỳ 1', reportName:'',              gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1',parentGroup: 'Học kỳ 1', gradingType: 'Normal',                               weight: '0', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: true},  isComment: false,  lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook:false, isSyncToCanvas: true },
    { code: 'CK2',     name: 'Cuối kỳ 2', reportName:'',              gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2',parentGroup: 'Học kỳ 2', gradingType: 'Normal',                               weight: '0', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: true},  isComment: false,  lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'MDDGK1',  name: 'Mức đạt được - GK1', reportName:'',     gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: 'HK1', semester: 'Học kỳ 1',parentGroup: 'Học kỳ 1', gradingType: 'Normal', weight: '0', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: true},  isComment: false,  lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'MDDCK1',  name: 'Mức đạt được - CK1', reportName:'',     gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: 'HK1', semester: 'Học kỳ 1',parentGroup: 'Học kỳ 1', gradingType: 'Normal', weight: '0', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: true},  isComment: false,  lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'MDDGK2',  name: 'Mức đạt được - GK2', reportName:'',     gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: 'HK2', semester: 'Học kỳ 2',parentGroup: 'Học kỳ 2', gradingType: 'Normal', weight: '0', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: true},  isComment: false,  lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'MDDCK2',  name: 'Mức đạt được - CK2', reportName:'',     gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: 'HK2', semester: 'Học kỳ 2',parentGroup: 'Học kỳ 2', gradingType: 'Normal', weight: '0', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: true},  isComment: false,  lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXGK1',   name: 'Nhận xét giữa kì 1', reportName:'',     gradingMechanism: '', semesterCode: 'HK1', semester: 'Học kỳ 1',parentGroup: 'Học kỳ 1', gradingType: 'Comment', weight: '', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: false}, isComment: true,  lineNumber: '' },
    { code: 'NXCK1',   name: 'Nhận xét cuối kì 1', reportName:'',     gradingMechanism: '', semesterCode: 'HK1', semester: 'Học kỳ 1',parentGroup: 'Học kỳ 1', gradingType: 'Comment', weight: '', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: false}, isComment: true,  lineNumber: '' },
    { code: 'NXGK2',   name: 'Nhận xét giữa kì 2', reportName:'',     gradingMechanism: '', semesterCode: 'HK2', semester: 'Học kỳ 2',parentGroup: 'Học kỳ 2', gradingType: 'Comment', weight: '', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: false}, isComment: true,  lineNumber: '' },
    { code: 'NXCK2',   name: 'Nhận xét cuối kì 2', reportName:'',     gradingMechanism: '', semesterCode: 'HK2', semester: 'Học kỳ 2',parentGroup: 'Học kỳ 2', gradingType: 'Comment', weight: '', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: false}, isComment: true,  lineNumber: '' },
    { code: 'TL',      name: 'Thi lại', reportName:'',                gradingMechanism: '10', semesterCode: '', semester: '',parentGroup: '',    gradingType: 'Normal',  weight: '0', gradingInput: {isReadOnly: false, isInputOrImportExcel: true, isFromTeacherGradebook: true},  isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
  ]
};

export const TH_MOET_MUCDATDUOC_DETAIL: GradingBookTemplateDetail = {
  code: 'TH_MOET_MUCDATDUOC',
  finalScore: 'CN',
  columns: [
    { code: 'CN',      name: 'Cuối năm',               reportName: '', gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: '',    semester: '',    parentGroup: '',    gradingType: 'Calculation', scheme: { calculatedItems: ['Học kỳ 2'],           calculationType: 'Grading conversion', minColumnsCount: 1 }, weight: '0', gradingInput: { isReadOnly: true,  isInputOrImportExcel: false, isFromTeacherGradebook: false }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'HK1',     name: 'Học kỳ 1',               reportName: '', gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Cuối năm', gradingType: 'Calculation', scheme: { calculatedItems: ['Mức đạt được - CK1'], calculationType: 'Grading conversion', minColumnsCount: 1 }, weight: '0', gradingInput: { isReadOnly: true,  isInputOrImportExcel: false, isFromTeacherGradebook: false }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'HK2',     name: 'Học kỳ 2',               reportName: '', gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Cuối năm', gradingType: 'Calculation', scheme: { calculatedItems: ['Mức đạt được - CK2'], calculationType: 'Grading conversion', minColumnsCount: 1 }, weight: '0', gradingInput: { isReadOnly: true,  isInputOrImportExcel: false, isFromTeacherGradebook: false }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'MDDGK1',  name: 'Mức đạt được - GK1',     reportName: '', gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                              weight: '0', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'MDDCK1',  name: 'Mức đạt được - CK1',     reportName: '', gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                              weight: '0', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXGK1',   name: 'Nhận xét giữa kì 1',     reportName: '', gradingMechanism: '',                                                                         semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Comment',                                                                                                                                weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'NXCK1',   name: 'Nhận xét cuối kì 1',     reportName: '', gradingMechanism: '',                                                                         semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Comment',                                                                                                                                weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'MDDGK2',  name: 'Mức đạt được - GK2',     reportName: '', gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                              weight: '0', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'MDDCK2',  name: 'Mức đạt được - CK2',     reportName: '', gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                              weight: '0', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXGK2',   name: 'Nhận xét giữa kì 2',     reportName: '', gradingMechanism: '',                                                                         semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Comment',                                                                                                                                weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'NXCK2',   name: 'Nhận xét cuối kì 2',     reportName: '', gradingMechanism: '',                                                                         semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Comment',                                                                                                                                weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'TL',      name: 'Thi lại',                 reportName: '', gradingMechanism: 'TH - Đánh giá môn học & hoạt động giáo dục Tiểu học', semesterCode: '',    semester: '',    parentGroup: '',    gradingType: 'Normal',                                                                                                                                              weight: '0', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
  ]
};

export const THCS_THPT_MOET_DGBD_DETAIL: GradingBookTemplateDetail = {
  code: 'THCS_THPT_MOET_DGBD',
  finalScore: 'CN',
  columns: [
    { code: 'CN',       name: 'Cuối năm',          reportName: '', gradingMechanism: '10', semesterCode: '',    semester: '',    parentGroup: '',    gradingType: 'Calculation', scheme: { calculatedItems: ['Học kỳ 1', 'Học kỳ 2'],                                     calculationType: 'Average', minColumnsCount: 1 }, weight: '0', gradingInput: { isReadOnly: true,  isInputOrImportExcel: false, isFromTeacherGradebook: false }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'HK1',      name: 'Học kỳ 1',          reportName: '', gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Cuối năm', gradingType: 'Calculation', scheme: { calculatedItems: ['TX1', 'TX2', 'TX3', 'TX4', 'TX5', 'Giữa kỳ', 'Cuối kỳ'], calculationType: 'Average', minColumnsCount: 1 }, weight: '1', gradingInput: { isReadOnly: true,  isInputOrImportExcel: false, isFromTeacherGradebook: false }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'TX1-HK1',  name: 'TX1',               reportName: '', gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                   weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX2-HK1',  name: 'TX2',               reportName: '', gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                   weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX3-HK1',  name: 'TX3',               reportName: '', gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                   weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX4-HK1',  name: 'TX4',               reportName: '', gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                   weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX5-HK1',  name: 'TX5',               reportName: '', gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                   weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'GK-HK1',   name: 'Giữa kỳ',           reportName: '', gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                   weight: '2', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXGK1',    name: 'Nhận xét giữa kì 1',reportName: '', gradingMechanism: '',   semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Comment',                                                                                                                                                  weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'CK-HK1',   name: 'Cuối kỳ',           reportName: '', gradingMechanism: '10', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                   weight: '3', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXCK1',    name: 'Nhận xét cuối kì 1',reportName: '', gradingMechanism: '',   semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Comment',                                                                                                                                                  weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'HK2',      name: 'Học kỳ 2',          reportName: '', gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Cuối năm', gradingType: 'Calculation', scheme: { calculatedItems: ['TX1', 'TX2', 'TX3', 'TX4', 'TX5', 'Giữa kỳ', 'Cuối kỳ'], calculationType: 'Average', minColumnsCount: 1 }, weight: '2', gradingInput: { isReadOnly: true,  isInputOrImportExcel: false, isFromTeacherGradebook: false }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'TX1-HK2',  name: 'TX1',               reportName: '', gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                   weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX2-HK2',  name: 'TX2',               reportName: '', gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                   weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX3-HK2',  name: 'TX3',               reportName: '', gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                   weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX4-HK2',  name: 'TX4',               reportName: '', gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                   weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX5-HK2',  name: 'TX5',               reportName: '', gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                   weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'GK-HK2',   name: 'Giữa kỳ',           reportName: '', gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                   weight: '2', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXGK2',    name: 'Nhận xét giữa kì 2',reportName: '', gradingMechanism: '',   semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Comment',                                                                                                                                                  weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'CK-HK2',   name: 'Cuối kỳ',           reportName: '', gradingMechanism: '10', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                   weight: '3', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXCK2',    name: 'Nhận xét cuối kì 2',reportName: '', gradingMechanism: '',   semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Comment',                                                                                                                                                  weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'TL',       name: 'Thi lại',            reportName: '', gradingMechanism: '10', semesterCode: '',    semester: '',    parentGroup: '',    gradingType: 'Normal',                                                                                                                                                   weight: '0', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
  ]
};

export const THCS_THPT_MOET_DGNX_DETAIL: GradingBookTemplateDetail = {
  code: 'THCS_THPT_MOET_DGNX',
  finalScore: 'CN',
  columns: [
    { code: 'CN',       name: 'Cuối năm',          reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: '',    semester: '',    parentGroup: '',    gradingType: 'Calculation', scheme: { calculatedItems: ['Học kỳ 1', 'Học kỳ 2'],                                     calculationType: 'Grading conversion', minColumnsCount: 1 }, weight: '0', gradingInput: { isReadOnly: true,  isInputOrImportExcel: false, isFromTeacherGradebook: false }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'HK1',      name: 'Học kỳ 1',          reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Cuối năm', gradingType: 'Calculation', scheme: { calculatedItems: ['TX1', 'TX2', 'TX3', 'TX4', 'TX5', 'Giữa kỳ', 'Cuối kỳ'], calculationType: 'Average',            minColumnsCount: 1 }, weight: '1', gradingInput: { isReadOnly: true,  isInputOrImportExcel: false, isFromTeacherGradebook: false }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'TX1-HK1',  name: 'TX1',               reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX2-HK1',  name: 'TX2',               reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX3-HK1',  name: 'TX3',               reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX4-HK1',  name: 'TX4',               reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX5-HK1',  name: 'TX5',               reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'GK-HK1',   name: 'Giữa kỳ',           reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXGK1',    name: 'Nhận xét giữa kì 1',reportName: '', gradingMechanism: '',                                           semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Comment',                                                                                                                                                          weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'CK-HK1',   name: 'Cuối kỳ',           reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXCK1',    name: 'Nhận xét cuối kì 1',reportName: '', gradingMechanism: '',                                           semesterCode: 'HK1', semester: 'Học kỳ 1', parentGroup: 'Học kỳ 1', gradingType: 'Comment',                                                                                                                                                          weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'HK2',      name: 'Học kỳ 2',          reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Cuối năm', gradingType: 'Calculation', scheme: { calculatedItems: ['TX1', 'TX2', 'TX3', 'TX4', 'TX5', 'Giữa kỳ', 'Cuối kỳ'], calculationType: 'Average',            minColumnsCount: 1 }, weight: '1', gradingInput: { isReadOnly: true,  isInputOrImportExcel: false, isFromTeacherGradebook: false }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
    { code: 'TX1-HK2',  name: 'TX1',               reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX2-HK2',  name: 'TX2',               reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX3-HK2',  name: 'TX3',               reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX4-HK2',  name: 'TX4',               reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'TX5-HK2',  name: 'TX5',               reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'GK-HK2',   name: 'Giữa kỳ',           reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXGK2',    name: 'Nhận xét giữa kì 2',reportName: '', gradingMechanism: '',                                           semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Comment',                                                                                                                                                          weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'CK-HK2',   name: 'Cuối kỳ',           reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Normal',                                                                                                                                                           weight: '1', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false, isSyncToCanvas: true },
    { code: 'NXCK2',    name: 'Nhận xét cuối kì 2',reportName: '', gradingMechanism: '',                                           semesterCode: 'HK2', semester: 'Học kỳ 2', parentGroup: 'Học kỳ 2', gradingType: 'Comment',                                                                                                                                                          weight: '',  gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: false }, isComment: true,  lineNumber: '' },
    { code: 'TL',       name: 'Thi lại',            reportName: '', gradingMechanism: 'THCS- THPT Đánh giá môn học bằng nhận xét', semesterCode: '',    semester: '',    parentGroup: '',    gradingType: 'Normal',                                                                                                                                                           weight: '0', gradingInput: { isReadOnly: false, isInputOrImportExcel: true,  isFromTeacherGradebook: true  }, isComment: false, lineNumber: '', isRounded: false, isDisplayOnTotalScoreGradeBook: false },
  ]
};